/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.carshop.application;

import java.util.List;

import ca.mcgill.ecse.carshop.model.*;
public class CarShopApplication {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new CarShopApplication().getGreeting());
    }
    
    /***Make the basic car shop***/
    static CarShop theCarShop = new CarShop();
    static Customer activeUser = null;
    
    /***Retrieve the basic car shop***/
    
    public static CarShop getCarshop() {
    	
		return theCarShop;
    }
    
    /***Methods for login***/
    
    public static boolean isLoggedIn() {
    	
		return (activeUser != null);
    }
    
    public static String login(String username, String pw) {
    	List<Customer> custs = theCarShop.getCustomers();
    	
    	boolean success = false;
    	for(Customer cust : custs)
	    {
	    	if(cust.getUsername().equals(username))
	    	{
	    		if(cust.getPassword().equals(pw))
	    		{
	    			success = true;
	    			activeUser = cust;
	    			break;
	    		}
	    	}
	    }
    	if(!success)
    	{
    		activeUser = null;
    		return "Username/password not found";
    	}
    	else
    	{
    		return "";
    	}
    }
}
