/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.carshop.application;

import java.sql.Date;
import java.sql.Time;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import ca.mcgill.ecse.carshop.model.*;
import ca.mcgill.ecse.carshop.model.Technician.TechnicianType;
public class CarShopApplication {
    public String getGreeting() {
        return "Welcome to The Car Shop!";
    }

 /*
 * main method to make the application functionnal
 * */  
    public static void main(String[] args) {
        System.out.println(new CarShopApplication().getGreeting());
        
        //configure the car shop
        setup();
        
        //for prompts
        boolean running = true;
        Scanner scan = new Scanner(System.in);
        
        //once it is running
        while(running)
        {
        	//verify if user is logged in before showing menu (Customer only for now)
        	if(!isLoggedIn())
        	{
	            System.out.println("\nThe Car Shop Main Menu");
	            System.out.println("\t\t1. Login");
	            System.out.println("\t\t2. Signup");
	            System.out.println("\t\t3. Quit");
	            System.out.print("Please Enter Your Option: ");
        	}
        	else
        	{
        		System.out.println("\nWelcome, " + activeUser.getUsername());
	            System.out.println("\t\t1. View/Update Appointment");
	            System.out.println("\t\t2. Book Appointment");
	            System.out.println("\t\t3. Quit");
	            System.out.print("Please Enter Your Option: ");
        	}        	

			int choice = 0;
			try{
				choice = scan.nextInt();
			}
			catch(Exception e)
			{
				System.out.println("Invalid option..");
				continue;
			}

            switch(choice)
            {
				// Login or view/update appointment
                case 1:
                {
                	if(!isLoggedIn())
                	{
						System.out.print("Please Enter Your Username: ");
						String username = scan.next();
						
						System.out.print("Please Enter Your Password: ");
						String password = scan.next();
						
						System.out.println(CarShopApplication.login(username, password));
                	}
                	else
                	{
                		if(activeUser.getAppointments().size() == 0)
                		{
                			System.out.println("You have no appointments");
                		}
                		else
                		{
                			List<Appointment> apts = activeUser.getAppointments();
                			for(Appointment apt : apts)
                			{
	                			System.out.println(apt.getBookableService().getName() + " on " + apt.getServiceBooking(0).getTimeSlot().getStartDate() + " at " + apt.getServiceBooking(0).getTimeSlot().getStartTime());
	
	                			System.out.print("Update? (y/n): ");
	    						if(scan.next().equals("y"))
	    						{
	    							System.out.print("Available Services:\r");

	    	                		List<BookableService> services = theCarShop.getBookableServices();
	    	                		for(BookableService service : services) {	
	    	                    			System.out.println( "- " + service.getName());
	    	                    	}
	    							System.out.print("Please Select your Service: ");
	    							String service = scan.next();
	    	                		TimeSlot oldSlot = apt.getServiceBooking(0).getTimeSlot();
	    	                		
	    	                		if(BookableService.hasWithName(service))
	    	                		{
	    	                			apt.delete();
	    	                			apt = theCarShop.addAppointment(activeUser, BookableService.getWithName(service));
	    	                		}
	    	                		else
	    	                		{
	    	                			System.out.println("That service does not exist");
	    	                		}
	    	                		
	    	                		System.out.println("The following are available time slots:");
	    	                		
	    	                		List<TimeSlot> slots = theCarShop.getTimeSlots();
	    	                		
	    	                		
    	                			int counter = 0;
    	                			int nono = 0;
    	                    		
    	                			for(TimeSlot slot : slots) {
    	                				counter++;
    	                				if (slot.isAvailable()){
    	                					nono++;
	    	                    			System.out.println(counter + ". " + slot.getStartDate() + ", " + slot.getStartTime());
	    	                    		}
    	                    		}
    	                    		
    	                    		if(nono == 0)
	    	                		{
	    	                			System.out.println("There are no available time slots.");
	    	                		}
	    	                		
    	                    		else {	
	    	                    		System.out.print("Please Select a New Time Slot From Above: ");
	    	                    		int opt = scan.nextInt();
	    	                    		
	    	                    		TimeSlot slot = theCarShop.getTimeSlot(opt-1);
	    	                    		oldSlot.changeAvailability();
	    	                    		slot.changeAvailability();
	    	                    		
	    	                    		theCarShop.addTimeSlot(usedSlots.get(0));
	    	                    		apt.addServiceBooking((Service) BookableService.getWithName(service), slot);
	    	                    		usedSlots.add(slot);
	    	                    		
	    	                    		System.out.print("Appointment Changed !");

	    	                		}
	    						}
                			}
                		}
                	}
                    break;
                }
				// Signup or book appointment
                case 2:
                {
                	if(!isLoggedIn())
                	{
                		System.out.print("Please Select a Username: ");
                		String username = scan.next();
                		
                		List<Customer> custs = theCarShop.getCustomers();
                		
                		boolean custExists = false;
                		for(Customer cust : custs)
            		    {
            		    	if(cust.getUsername().equals(username))
            		    	{
            		    		custExists = true;
            		    		System.out.println("That username is taken");
            		    		break;
            		    	}
            		    }
            		    if(!custExists)
            		    {
            		    	System.out.print("Please Select a Password: ");
    						String password = scan.next();
            		    	theCarShop.addCustomer(username, password);
            		    }
                	}
                	else
                	{
                		System.out.print("Available Services:\r");

                		List<BookableService> services = theCarShop.getBookableServices();
                		for(BookableService service : services) {	
                    			System.out.println( "- " + service.getName());
                    	}
                		System.out.print("Please Select your Service: ");
                		
                		String service = scan.next();
                		
                		Appointment apt;
                		if(BookableService.hasWithName(service))
                		{
                			apt = theCarShop.addAppointment(activeUser, BookableService.getWithName(service));
                		}
                		else
                		{
                			System.out.println("That service does not exist");
                			break;
                		}
                		
                		System.out.println("The following are available time slots:");
                		
                		List<TimeSlot> slots = theCarShop.getTimeSlots();
                		
                		int counter = 0;
                		int nono=0;
                		
            			for(TimeSlot slot : slots) {
            				counter++;
            				if (slot.isAvailable()){
            					nono++;
                    			System.out.println(counter + ". " + slot.getStartDate() + ", " + slot.getStartTime());
                    		}
                		}
                		
                		if(nono == 0)
                		{
                			System.out.println("*There are no available time slots.*");
                		}
                		
                		else {	
                    		System.out.print("Please Select a Time Slot From Above: ");
                    		int opt = scan.nextInt();
                    		
                    		TimeSlot slot = theCarShop.getTimeSlot(opt-1);
                    		slot.changeAvailability();
                    		apt.addServiceBooking((Service) BookableService.getWithName(service), slot);
                    		usedSlots.add(slot);
                    		
                    		System.out.print("Appointment registered !");

                		}
                		
                	}
					
                    break;
                }
				// Exit Application
                case 3:
                {
                    running = false;
                    scan.close();
                    activeUser = null;
                    theCarShop.delete();
                    System.out.println("Thank you for using The Car Shop!");
                    break;
                }
				// Invalid
                default:
                {
                    System.out.println("Invalid option \'" + choice + "\'");
                    break;
                }
            }
        }        
    }
    
/*
 * instances to make the basic car shop
 * */
    static CarShop theCarShop = new CarShop();
    static Customer activeUser = null;
    static List<TimeSlot> usedSlots = new ArrayList<TimeSlot>();
    
/*
 * method to setup/initialte a simulation of the functioning app
 * */
    private static void setup()
    {
    	theCarShop.addCustomer("user", "test");
    	
    	Owner theOwner = new Owner("owner", "owner", theCarShop);
    	theCarShop.setOwner(theOwner);
    	
    	Technician engineTech = theCarShop.addTechnician("Engine-Technician", "Engine-Technician", TechnicianType.Engine);
    	Garage engineGarage = theCarShop.addGarage(engineTech);
    	
    	theCarShop.addBookableService(new Service("Engine-Swap", theCarShop, 5, engineGarage));
    	theCarShop.addBookableService(new Service("Oil-Change", theCarShop, 1, engineGarage));
    	theCarShop.addBookableService(new Service("Tires", theCarShop, 1, engineGarage));
    	
    	
    	theCarShop.addTimeSlot(Date.valueOf("2021-06-11"), Time.valueOf("13:00:00"), Date.valueOf("2021-06-11"), Time.valueOf("14:00:00"));
    	theCarShop.addTimeSlot(Date.valueOf("2021-06-14"), Time.valueOf("09:00:00"), Date.valueOf("2021-06-14"), Time.valueOf("14:00:00"));
    }
    
/*
 * method to retrieve the basic car shop in main
 * */
    public static CarShop getCarshop() {
    	
		return theCarShop;
    }
    
/*
 * Methods for user to login
 * */    
    public static boolean isLoggedIn() {
    	
		return (activeUser != null);
    }
    
    public static String login(String username, String pw) {
    	List<Customer> custs = theCarShop.getCustomers();
    	
    	boolean success = false;
    	for(Customer cust : custs)
	    {
	    	if(cust.getUsername().equals(username))
	    	{
	    		if(cust.getPassword().equals(pw))
	    		{
	    			success = true;
	    			activeUser = cust;
	    			break;
	    		}
	    	}
	    }
    	if(!success)
    	{
    		activeUser = null;
    		return "Username/password not found";
    	}
    	else
    	{
    		return "";
    	}
    }
}
